---
- name: Provision Rocky Linux server
  hosts: localhost
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Install essential packages
      dnf:
        name:
          - nano
          - openssh-server
          - epel-release
        state: present

    - name: Start and enable sshd
      systemd:
        name: sshd
        state: started
        enabled: yes

    - name: Ensure new user exists
      user:
        name: "{{ new_user }}"
        groups: wheel
        append: yes
        create_home: yes

    - name: Set password for new user
      ansible.builtin.command: "echo '{{ new_user }}:changeme' | chpasswd"
      no_log: true

    - name: Disable root SSH login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s+.*'
        line: 'PermitRootLogin no'
        state: present
        backup: yes

    - name: Restart SSH service
      systemd:
        name: sshd
        state: restarted
    
    - name: Install EPEL 
      dnf:
       name: epel-release
          
    - name: Download latest Neofetch script from GitHub
      get_url:
        url: https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch
        dest: /tmp/neofetch
        mode: '0755'

    - name: Move neofetch to /usr/bin
      command: mv /tmp/neofetch /usr/bin/neofetch
      args:
        creates: /usr/bin/neofetch

    - name: Ensure Neofetch runs on login for new user
      lineinfile:
        path: "/home/{{ new_user }}/.bashrc"
        line: "neofetch"
        create: yes
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0644'

    - name: Ensure 'ansible' group exists
      group:
        name: ansible
        state: present

    - name: Ensure 'ansible' user exists and is in 'ansible' group
      user:
        name: ansible
        system: yes
        shell: /sbin/nologin
        groups: ansible
        append: yes
        create_home: no

    - name: Ensure /opt/ansible-provision directory exists
      file:
        path: /opt/ansible-provision
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Set /opt/ansible-provision as a trusted Git directory (system-wide)
      command: git config --system --add safe.directory /opt/ansible-provision

    - name: Ensure ansible-pull log file exists in /opt
      file:
        path: /opt/ansible-provision/ansible-pull.log
        state: touch
        owner: ansible
        group: ansible
        mode: '0644'

    - name: Create cronjob to run ansible-pull every 5 minutes
      cron:
        name: "Ansible Pull"
        user: ansible
        minute: "*/5"
        job: >
          /usr/bin/ansible-pull -U https://github.com/lumpy-custard/Ansible_Provisioning_Test.git
          -d /opt/ansible-provision
          -i localhost,
          provision_rocky/playbook.yml >> /opt/ansible-provision/ansible-pull.log 2>&1
